### ISSUE TITLE
[BUG] nested fields should be placed after unnested ones

### ISSUE THREAD

**Issue by poly000** [yanganto/toml-example#18]
toml_example will place items in the order they were defined, this caused this semantic bug for the generated example

**Comment by yanganto** [comment]
Hi @poly000 

Thanks for reporting.
Could you give a more solid use case for this? 

For example, you can give a simple code snippet this way, so I can easily help you.
```rust
use toml_example::TomlExample;
#[derive(TomlExample)]
struct Config {
    /// Config.a is an optional number
    #[toml_example(require)]
    a: Option<usize>,
    /// Config.b is an optional string
    #[toml_example(require)]
    b: Option<String>,
    #[toml_example(require)]
    #[toml_example(default = "third")]
    c: Option<String>,
    #[toml_example(skip)]
    d: usize,
}
assert_eq!(Config::toml_example(),
r#"# Config.a is an optional number
a = 0

# Config.b is an optional string
b = ""

c = "third"

"#)
```

**Comment by poly000** [comment]
> Hi @poly000
> 
> Thanks for reporting. Could you give a more solid use case for this?
> 
> For example, you can give a simple code snippet in this way, so I can easily help you.
> 
> ```rust
> use toml_example::TomlExample;
> #[derive(TomlExample)]
> struct Config {
>     /// Config.a is an optional number
>     #[toml_example(require)]
>     a: Option<usize>,
>     /// Config.b is an optional string
>     #[toml_example(require)]
>     b: Option<String>,
>     #[toml_example(require)]
>     #[toml_example(default = "third")]
>     c: Option<String>,
>     #[toml_example(skip)]
>     d: usize,
> }
> assert_eq!(Config::toml_example(),
> r#"# Config.a is an optional number
> a = 0
> 
> # Config.b is an optional string
> b = ""
> 
> c = "third"
> 
> "#)
> ```

```rust

assert_eq!(Config::toml_example(),
r#"# Config.a is an optional number
a = 0

# Config.b is an optional string
b = ""

c = "third"

"#)
```

> Hi @poly000
> 
> Thanks for reporting. Could you give a more solid use case for this?
> 
> For example, you can give a simple code snippet in this way, so I can easily help you.
> 
> ```rust
> use toml_example::TomlExample;
> #[derive(TomlExample)]
> struct Config {
>     /// Config.a is an optional number
>     #[toml_example(require)]
>     a: Option<usize>,
>     /// Config.b is an optional string
>     #[toml_example(require)]
>     b: Option<String>,
>     #[toml_example(require)]
>     #[toml_example(default = "third")]
>     c: Option<String>,
>     #[toml_example(skip)]
>     d: usize,
> }
> assert_eq!(Config::toml_example(),
> r#"# Config.a is an optional number
> a = 0
> 
> # Config.b is an optional string
> b = ""
> 
> c = "third"
> 
> "#)
> ```

```rust
#[derive(TomlExample)]
struct Foo {
    a: String,
}

#[derive(TomlExample)]
struct Bar{
    #[toml_example(nested)]
    foo: Foo,
    b: String,
};

println!("{}", Foo::toml_example());
```

expected:
```toml
b = ""

[foo]
a = ""
```

actual output:
```toml
[foo]
a = ""

b = ""
```
