### ISSUE TITLE
[BUG] 'r#' in field name should be removed

### ISSUE THREAD

**Issue by poly000** [yanganto/toml-example#19]
workaround: use `#[serde(rename)]` instead

**Comment by yanganto** [comment]
Hi @poly000,

Could you point out which `r#` should be removed?
If there is a better way to handle multiline strings without verbose, it will be appreciated.

You can open a PR for this, that will be nice and clear.

**Comment by poly000** [comment]
> Hi @poly000,
> 
> Could you point out which `r#` should be removed? If there is a better way to handle multiline strings without verbose, it will be appreciated.
> 
> You can open a PR for this, that will be nice and clear.

```rust
#[derive(TomlExample)]
struct Foo {
    r#type: String,
}

#[derive(TomlExample)]
struct Bar{
    #[toml_example(nested)]
    foo: Foo,
};

println!("{}", Foo::toml_example());
```

expected:
```toml
[foo]
type = ""
```

actual output:
```toml
[foo]
r#type = ""
```
